#ifndef LIBIRCCLIENT_GLOBAL_H
#define LIBIRCCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBIRCCLIENT_LIBRARY)
#  define LIBIRCCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBIRCCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBIRCCLIENT_GLOBAL_H
